% clc;
% clear;
% load('E:\study\hj\ma\ALLSiftVectors.mat','countVectors');
% load('E:\study\hj\ma\ALLGistFea.mat','GistFeats');
% load('E:\study\hj\ma\hog_right_43.mat','hog');
% load('E:\study\hj\ma\ALLLBPFea.mat','LBPFeats');
% load('E:\study\hj\ma\resnet152R.mat','resnet152R');
% load('E:\study\hj\ma\resnet50R.mat','resnet50R');
% load('E:\study\hj\ma\densenet121R.mat','densenet121R');
% load('E:\study\hj\ma\densenet161R.mat','densenet161R');
% load('E:\study\hj\ma\vgg16aR.mat','vgg16aR');
% load('E:\study\hj\ma\vgg16R.mat','vgg16R');
% load('E:\study\hj\ma\restart\ma_result\dca\4\HS.mat','HS');
% load('E:\study\hj\ma\restart\ma_result\dca\4\LHS.mat','LHS');
% load('E:\study\hj\ma\restart\ma_result\dca\4\LHSG.mat','LHSG');
% load('E:\study\hj\ma\restart\ma_result\dca\4\V16VA16.mat','V16VA16');
% load('E:\study\hj\ma\restart\ma_result\dca\4\V16VA16R50.mat','V16VA16R50');
% load('E:\study\hj\ma\restart\ma_result\dca\4\V16VA16R50D121.mat','V16VA16R50D121');
% load('E:\study\hj\ma\restart\ma_result\dca\4\LHSGV16VA16R50D121.mat','LHSGV16VA16R50D121');
% HT1 = [HS';LHS';]';
% save('E:\study\hj\ma\restart\ma_result\dca\4\contact\HT1.mat','HT1');
% csvwrite('E:\study\hj\ma\restart\ma_result\dca\4\contact\HT1.csv',HT1);
% HT2 = [HT1';LHSG']';
% save('E:\study\hj\ma\restart\ma_result\dca\4\contact\HT2.mat','HT2');
% csvwrite('E:\study\hj\ma\restart\ma_result\dca\4\contact\HT2.csv',HT2);
% HD1 = [V16VA16';V16VA16R50']';
% save('E:\study\hj\ma\restart\ma_result\dca\4\contact\HD1.mat','HD1');
% csvwrite('E:\study\hj\ma\restart\ma_result\dca\4\contact\HD1.csv',HD1);
% HD2 = [HD1';V16VA16R50D121']';
% save('E:\study\hj\ma\restart\ma_result\dca\4\contact\HD2.mat','HD2');
% csvwrite('E:\study\hj\ma\restart\ma_result\dca\4\contact\HD2.csv',HD2);
% HT2_V16VA16 = [HT2';V16VA16']';
% save('E:\study\hj\ma\restart\ma_result\dca\4\contact\HT2_V16VA16.mat','HT2_V16VA16');
% csvwrite('E:\study\hj\ma\restart\ma_result\dca\4\contact\HT2_V16VA16.csv',HT2_V16VA16);
% HT2_HD1 = [HT2';HD1']';
% save('E:\study\hj\ma\restart\ma_result\dca\4\contact\HT2_HD1.mat','HT2_HD1');
% csvwrite('E:\study\hj\ma\restart\ma_result\dca\4\contact\HT2_HD1.csv',HT2_HD1);
% HT2_HD2 = [HT2';HD2']';
% save('E:\study\hj\ma\restart\ma_result\dca\4\contact\HT2_HD2.mat','HT2_HD2');
% csvwrite('E:\study\hj\ma\restart\ma_result\dca\4\contact\HT2_HD2.csv',HT2_HD2);
% HT1_V16VA16 = [HT1';V16VA16']';
% save('E:\study\hj\ma\restart\ma_result\dca\4\contact\HT1_V16VA16.mat','HT1_V16VA16');
% csvwrite('E:\study\hj\ma\restart\ma_result\dca\4\contact\HT1_V16VA16.csv',HT1_V16VA16);
% HT1_HD1 = [HT1';HD1']';
% save('E:\study\hj\ma\restart\ma_result\dca\4\contact\HT1_HD1.mat','HT1_HD1');
% csvwrite('E:\study\hj\ma\restart\ma_result\dca\4\contact\HT1_HD1.csv',HT1_HD1);
% HT1_HD2 = [HT1';HD2']';
% save('E:\study\hj\ma\restart\ma_result\dca\4\contact\HT1_HD2.mat','HT1_HD2');
% csvwrite('E:\study\hj\ma\restart\ma_result\dca\4\contact\HT1_HD2.csv',HT1_HD2);
% HD1_HS = [HD1';HS']';
% save('E:\study\hj\ma\restart\ma_result\dca\4\contact\HD1_HS.mat','HD1_HS');
% csvwrite('E:\study\hj\ma\restart\ma_result\dca\4\contact\HD1_HS.csv',HD1_HS);
% HD1_HT1 = [HD1';HT1']';
% save('E:\study\hj\ma\restart\ma_result\dca\4\contact\HD1_HT1.mat','HD1_HT1');
% csvwrite('E:\study\hj\ma\restart\ma_result\dca\4\contact\HD1_HT1.csv',HD1_HT1);
% HD1_HT2 = [HD1';HT2']';
% save('E:\study\hj\ma\restart\ma_result\dca\4\contact\HD1_HT2.mat','HD1_HT2');
% csvwrite('E:\study\hj\ma\restart\ma_result\dca\4\contact\HD1_HT2.csv',HD1_HT2);
% HD2_HS = [HD2';HS']';
% save('E:\study\hj\ma\restart\ma_result\dca\4\contact\HD2_HS.mat','HD2_HS');
% csvwrite('E:\study\hj\ma\restart\ma_result\dca\4\contact\HD2_HS.csv',HD2_HS);
% HD2_HT1 = [HD2';HT1']';
% save('E:\study\hj\ma\restart\ma_result\dca\4\contact\HD2_HT1.mat','HD2_HT1');
% csvwrite('E:\study\hj\ma\restart\ma_result\dca\4\contact\HD2_HT1.csv',HD2_HT1);
% HD2_HT2 = [HD2';HT2']';
% save('E:\study\hj\ma\restart\ma_result\dca\4\contact\HD2_HT2.mat','HD2_HT2');
% csvwrite('E:\study\hj\ma\restart\ma_result\dca\4\contact\HD2_HT2.csv',HD2_HT2);
% 
% HS_V16VA16 = [HS';V16VA16']';
% save('E:\study\hj\ma\restart\ma_result\dca\4\contact\HS_V16VA16.mat','HS_V16VA16');
% csvwrite('E:\study\hj\ma\restart\ma_result\dca\4\contact\HS_V16VA16.csv',HS_V16VA16);
% S = rank(countVectors);
% G = rank(GistFeats);
% GLS = importdata('E:\study\DCA\FMD\result\GLS.csv')';
% VA16V16R152 = importdata('E:\study\DCA\FMD\result\VA16V16R152.csv')';
% V16VA16R50D121 = importdata('E:\study\hj\ma\restart\ma_result\dca\test\V16VA16R50D121.csv')';
% test1 = importdata('E:\study\hj\ma\restart\m_test_7525.csv');
% test2 = importdata('E:\study\hj\ma\restart\m2_test_7525.csv');
% test3 = importdata('E:\study\hj\ma\restart\m3_test_7525.csv');
% test4 = importdata('E:\study\hj\ma\restart\m4_test_7525.csv');
% save('E:\study\hj\ma\restart\test1.mat','test1');
% save('E:\study\hj\ma\restart\test2.mat','test2');
% save('E:\study\hj\ma\restart\test3.mat','test3');
% save('E:\study\hj\ma\restart\test4.mat','test4');
% H = rank(hog);
% L = rank(LBPFeats);
load('E:\study\my01\mat\REAL\resnet50R.mat');
load('E:\study\my01\mat\REAL\resnet152R2.mat');
load('E:\study\my01\mat\REAL\resnet101R2.mat');
load('E:\study\my01\mat\REAL\resnetxt50R.mat');
load('E:\study\my01\mat\REAL\resnetxt101R.mat');
load('E:\study\my01\mat\REAL\senet154R.mat');
load('E:\study\my01\mat\REAL\seresnet50Rn2.mat');
load('E:\study\my01\mat\REAL\seresnet101R2n.mat');
load('E:\study\my01\mat\REAL\seresnet152R2n.mat');
load('E:\study\my01\mat\REAL\seresnetxt50R.mat');
load('E:\study\my01\mat\REAL\seresnetxt101R.mat');
R152 = rank(resnet152R);
R50 = rank(resnet50R);
R101 = rank(resnet101R);
RXT50 = rank(resnetxt50R);
RXT101 = rank(resnetxt101R);
SE154 = rank(senet154R);
SR152 = rank(seresnet152R);
SR50 = rank(seresnet50Rn2);
SR101 = rank(seresnet101R);
SRXT50 = rank(seresnetxt50R);
SRXT101 = rank(seresnetxt101R);
